#ifndef _LIB_FUNC_ATTR_H
#define _LIB_FUNC_ATTR_H

#define USART_USARTCLOSE_ATTR
#define USART_USARTINIT_ATTR
#define USART_USARTREAD_ATTR
#define USART_USARTREADBYTE_ATTR
#define USART_USARTSENDBYTE_ATTR
#define USART_USARTUNREADBYTES_ATTR
#define USART_USARTSENDSTRING_ATTR

#define CHKSUM_CHECKSUM8BIT_ATTR
#define CHKSUM_CHECKSUM16BIT_ATTR

#define UTIL_SOFTRESET_ATTR

#endif // _LIB_FUNC_ATTR_H
